In [1]:
import joblib

import pandas as pd
import numpy as np


from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler , MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [2]:
train = pd.read_csv('../data/train_ver03.csv', index_col='STU_ID')
train.head()

,BYSTUWT,BYSEX,BYRACE,BYSTLANG,BYHOMLNG,BYSTLNG2,BYDOB_P,BYFCOMP,BYPARED,BYMOTHED,...,BYS24D,BYS24E,BYS28,BYS71A,BYS71B,BYS71C,BYS71D,BYS71E,BYS71F,F3ONET2CURR
STU_ID,,,,,,,,,,,,,,,,,,,,,
101102,83.57963,2.0,2.0,0.0,4.0,2,198605.0,1.0,5.0,5.0,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,29
101104,292.12550,2.0,7.0,1.0,1.0,4,198601.0,1.0,2.0,2.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,27
101105,235.78220,2.0,3.0,1.0,1.0,4,198607.0,5.0,2.0,2.0,...,1.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,39
101106,178.95130,2.0,4.0,0.0,2.0,2,198511.0,1.0,1.0,1.0,...,1.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,29
101108,192.43040,1.0,4.0,1.0,1.0,4,198607.0,1.0,6.0,6.0,...,2.0,1.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,53

In [3]:
y = train.F3ONET2CURR
x = train.drop(columns='F3ONET2CURR')

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, stratify=y)

In [5]:
y_train.value_counts(normalize=True)

43    0.145058
41    0.088669
11    0.086526
29    0.073399
25    0.071256
35    0.068444
13    0.058398
51    0.048219
39    0.046209
31    0.041789
53    0.036030
27    0.034557
47    0.032949
49    0.032146
15    0.029467
33    0.025717
21    0.023172
17    0.020493
19    0.018886
37    0.018618
Name: F3ONET2CURR, dtype: float64

In [6]:
y_test.value_counts(normalize=True)

43    0.145038
41    0.088791
11    0.086782
29    0.073524
25    0.071113
35    0.068702
13    0.058658
51    0.048212
39    0.046203
31    0.041784
53    0.035757
27    0.034552
47    0.032945
49    0.032141
15    0.029329
33    0.025713
21    0.022901
17    0.020490
19    0.018883
37    0.018481
Name: F3ONET2CURR, dtype: float64

In [7]:
import joblib
with open('../data/my_val.pkl2', 'wb') as f:
    joblib.dump({'x':x_train,
                 'y':y_train,
                 'val_x':x_test,
                 'val_y':y_test},f)

In [4]:
test = pd.read_csv('../data/test_ver03.csv', index_col='STU_ID')
test = test.drop(columns='F3ONET2CURR')
test.head()

,BYSTUWT,BYSEX,BYRACE,BYSTLANG,BYHOMLNG,BYSTLNG2,BYDOB_P,BYFCOMP,BYPARED,BYMOTHED,...,BYS24C,BYS24D,BYS24E,BYS28,BYS71A,BYS71B,BYS71C,BYS71D,BYS71E,BYS71F
STU_ID,,,,,,,,,,,,,,,,,,,,,
310221,292.1255,2.0,6.0,1.0,1.0,4,198412.0,2.0,4.0,4.0,...,4.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,0.0
228218,281.6741,1.0,7.0,1.0,1.0,4,198507.0,6.0,1.0,1.0,...,3.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
179231,275.0641,1.0,7.0,1.0,1.0,4,198607.0,1.0,4.0,4.0,...,3.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
215101,149.2901,2.0,3.0,1.0,1.0,4,198507.0,2.0,3.0,1.0,...,4.0,1.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
245121,186.5067,1.0,7.0,1.0,1.0,4,198601.0,5.0,3.0,3.0,...,2.0,2.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0

In [17]:
with open('../data/my_val.pkl2', 'rb') as f:
    data = joblib.load(f)
locals().update(data)
del data
np.random.seed(1118)

## 1 ExtraTreesClassifier

In [5]:
from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier

In [6]:
# pipe = Pipeline([('ì „ì²˜ë¦¬',MinMaxScaler()), 
#                 ('ì•Œê³ ë¦¬ì¦˜', ExtraTreesClassifier(max_depth=20, n_estimators=300))])

# pipe = Pipeline([('ì „ì²˜ë¦¬', None),('ì•Œê³ ë¦¬ì¦˜', ExtraTreesClassifier(max_depth=18, n_estimators=300))])

pipe = Pipeline([('ì „ì²˜ë¦¬',MinMaxScaler()), 
                ('ì•Œê³ ë¦¬ì¦˜', ExtraTreesClassifier(max_depth=16, n_estimators=300, max_features='auto',class_weight='balanced', criterion='gini', min_samples_leaf=8))])

In [7]:
pipe.fit(x,y)

Pipeline(steps=[('ì „ì²˜ë¦¬', MinMaxScaler()),
                ('ì•Œê³ ë¦¬ì¦˜',
                 ExtraTreesClassifier(class_weight='balanced', max_depth=16,
                                      min_samples_leaf=8, n_estimators=300))])

In [67]:
from sklearn.metrics import accuracy_score
accuracy_score(val_y, pipe.predict(val_x))

0.21936520691040579

In [8]:
pred = pipe.predict(test)
pred

array([39, 49, 21, ..., 39, 39, 17], dtype=int64)

In [9]:
pred.shape

(2479,)

In [10]:
submission = pd.DataFrame(pred, index=test.index, columns=['PRED']).reset_index()
submission

      STU_ID  PRED
0     310221    39
1     228218    49
2     179231    21
3     215101    37
4     245121    51
...      ...   ...
2474  439214    25
2475  106206    13
2476  272131    39
2477  350228    39
2478  297108    17

[2479 rows x 2 columns]

In [11]:
submission.to_csv('my_pred24.csv', index=False)

## 2.One Vs All

In [12]:
import joblib

import pandas as pd
import numpy as np


from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler , MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [13]:
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier

In [3]:
with open('../data/my_val.pkl2', 'rb') as f:
    data = joblib.load(f)
locals().update(data)
del data
np.random.seed(1234)

In [20]:
# ovr_clf = OneVsRestClassifier(SVC(gamma='auto', random_state=42))
# ovr_clf.fit(x,y)
# ovo_clf = OneVsOneClassifier(RandomForestClassifier(max_depth=16, n_estimators=300))
ovr_clf = OneVsRestClassifier(RandomForestClassifier(max_depth=16, n_estimators=300))
ovr_clf.fit(x,y)

OneVsRestClassifier(estimator=RandomForestClassifier(max_depth=16,
                                                     n_estimators=300))

In [ ]:
accuracy_score(val_y, ovr_clf.predict(val_x))

In [21]:
pred = ovr_clf.predict(test)
pred

array([43, 51, 43, ..., 43, 43, 43], dtype=int64)

In [22]:
pred.shape

(2479,)

In [23]:
submission = pd.DataFrame(pred, index=test.index, columns=['PRED']).reset_index()
submission

      STU_ID  PRED
0     310221    43
1     228218    51
2     179231    43
3     215101    43
4     245121    51
...      ...   ...
2474  439214    27
2475  106206    13
2476  272131    43
2477  350228    43
2478  297108    43

[2479 rows x 2 columns]

In [24]:
submission.to_csv('my_pred26.csv', index=False)

In [25]:
my_class = y.unique()

In [26]:
my_class

array([29, 27, 39, 53, 13, 43, 51, 11, 21, 17, 47, 15, 25, 31, 35, 33, 41,
       49, 19, 37], dtype=int64)

In [27]:
my_models = []

for s in my_class:
    target = x.loc[y[y==s].index]
    non_target = x.loc[y[y!=s].index]
      # undersamplingì½”ë“œ
#     non_target = x.loc[y[y!=s].index].sample(len(target))
    my_sample=pd.concat([target, non_target])
    my_sample = my_sample.sample(len(my_sample))
    my_y = pd.concat([pd.Series(1, index=y.loc[target.index].index),
                     pd.Series(0, index=y.loc[non_target.index].index)])
    my_y = my_y.loc[my_sample.index]
    pipe = Pipeline([('ì „ì²˜ë¦¬',MinMaxScaler()), 
                         ('ì•Œê³ ë¦¬ì¦˜', RandomForestClassifier(max_depth=16, n_estimators=300))])
                     
#     pipe = Pipeline([('ì „ì²˜ë¦¬', MinMaxScaler()), ('ì•Œê³ ë¦¬ì¦˜', XGBClassifier(objective='binary:logistic',n_estimators= 125, max_depth= 5, learning_rate= 0.04))])
    pipe.fit(my_sample, my_y)
    my_models.append(pipe)

In [20]:
pred = np.zeros((len(val_x), len(my_class)))
for i,m in enumerate(my_models):
    p = m.predict_proba(val_x)[:,1]
    pred[:,i] = p
pred_class = [my_class[i] for i in pred.argmax(axis=1)]

In [21]:
accuracy_score(val_y, pred_class)

0.2635596625150663

In [22]:
pred.shape

(2489, 20)

In [23]:
with open('../data/one-vs-all.pkl', 'wb') as f:
    joblib.dump({'my_models' : my_models},f)

In [28]:
pred = np.zeros((len(test),len(my_class)))
for i, m in enumerate(my_models):
    p = m.predict_proba(test)[:,1]
    pred[:,i] = p
pred_class = [my_class[i] for i in pred.argmax(axis=1)]
pred_class

[43,
 51,
 43,
 35,
 51,
 25,
 43,
 17,
 53,
 43,
 43,
 25,
 13,
 43,
 13,
 43,
 43,
 43,
 43,
 43,
 25,
 13,
 43,
 21,
 13,
 43,
 43,
 25,
 43,
 43,
 41,
 43,
 33,
 11,
 43,
 25,
 29,
 43,
 43,
 17,
 43,
 19,
 43,
 43,
 19,
 43,
 25,
 29,
 35,
 25,
 43,
 43,
 43,
 47,
 15,
 43,
 43,
 43,
 43,
 43,
 43,
 29,
 15,
 43,
 11,
 43,
 51,
 43,
 51,
 43,
 43,
 43,
 43,
 43,
 51,
 43,
 47,
 43,
 43,
 15,
 43,
 11,
 43,
 43,
 43,
 43,
 51,
 43,
 43,
 11,
 11,
 15,
 43,
 11,
 29,
 41,
 43,
 43,
 43,
 29,
 47,
 13,
 29,
 29,
 11,
 29,
 13,
 41,
 25,
 29,
 43,
 51,
 43,
 17,
 29,
 51,
 17,
 25,
 43,
 29,
 25,
 43,
 43,
 43,
 13,
 43,
 17,
 35,
 29,
 29,
 13,
 29,
 13,
 33,
 43,
 43,
 43,
 17,
 25,
 11,
 35,
 43,
 43,
 11,
 43,
 49,
 43,
 29,
 43,
 29,
 13,
 43,
 11,
 43,
 29,
 43,
 43,
 43,
 43,
 25,
 43,
 29,
 13,
 43,
 53,
 49,
 43,
 35,
 43,
 25,
 29,
 51,
 15,
 29,
 53,
 47,
 13,
 25,
 43,
 43,
 29,
 25,
 25,
 47,
 43,
 43,
 41,
 29,
 29,
 43,
 29,
 43,
 43,
 25,
 43,
 51,
 43,
 19,
 25,
 13,
 43,
 41,
 29,
 43,
 25,
 27,
 43,
 25,
 43,
 25,
 43,
 25,
 25,
 43,
 39,
 13,
 43,
 51,
 43,
 13,
 43,
 43,
 11,
 43,
 43,
 43,
 43,
 25,
 35,
 43,
 51,
 31,
 11,
 41,
 43,
 43,
 43,
 21,
 25,
 51,
 29,
 51,
 29,
 47,
 47,
 43,
 43,
 43,
 27,
 43,
 43,
 43,
 35,
 43,
 29,
 43,
 11,
 13,
 43,
 51,
 29,
 43,
 43,
 43,
 43,
 27,
 43,
 43,
 43,
 29,
 13,
 35,
 43,
 13,
 25,
 29,
 43,
 43,
 13,
 47,
 25,
 29,
 29,
 43,
 43,
 51,
 43,
 43,
 29,
 13,
 13,
 43,
 43,
 39,
 25,
 43,
 43,
 11,
 29,
 43,
 43,
 29,
 29,
 43,
 25,
 43,
 29,
 43,
 43,
 35,
 43,
 35,
 29,
 19,
 51,
 11,
 25,
 29,
 31,
 43,
 41,
 13,
 29,
 25,
 11,
 43,
 13,
 13,
 43,
 17,
 43,
 13,
 13,
 13,
 43,
 43,
 43,
 43,
 25,
 51,
 29,
 51,
 47,
 43,
 43,
 35,
 27,
 29,
 43,
 35,
 43,
 17,
 47,
 11,
 43,
 29,
 11,
 43,
 43,
 49,
 43,
 29,
 13,
 41,
 51,
 29,
 43,
 15,
 43,
 29,
 35,
 25,
 11,
 43,
 31,
 13,
 17,
 51,
 29,
 29,
 41,
 43,
 43,
 43,
 13,
 43,
 43,
 43,
 11,
 41,
 43,
 11,
 11,
 43,
 43,
 29,
 13,
 43,
 11,
 41,
 13,
 43,
 25,
 43,
 43,
 47,
 35,
 29,
 29,
 29,
 43,
 43,
 29,
 43,
 29,
 43,
 13,
 43,
 43,
 43,
 35,
 29,
 43,
 43,
 27,
 43,
 49,
 11,
 29,
 43,
 43,
 43,
 43,
 27,
 43,
 43,
 25,
 25,
 29,
 49,
 25,
 43,
 43,
 43,
 43,
 25,
 29,
 13,
 43,
 29,
 43,
 25,
 53,
 13,
 25,
 25,
 47,
 29,
 51,
 43,
 43,
 43,
 49,
 11,
 47,
 43,
 29,
 43,
 13,
 43,
 29,
 43,
 29,
 43,
 43,
 13,
 51,
 51,
 25,
 39,
 29,
 35,
 29,
 43,
 43,
 25,
 43,
 29,
 29,
 43,
 31,
 49,
 29,
 43,
 29,
 35,
 43,
 51,
 43,
 17,
 25,
 43,
 43,
 35,
 43,
 43,
 35,
 43,
 43,
 13,
 43,
 43,
 43,
 43,
 43,
 43,
 35,
 43,
 13,
 43,
 43,
 43,
 43,
 17,
 11,
 43,
 43,
 43,
 13,
 43,
 47,
 43,
 29,
 43,
 13,
 29,
 29,
 43,
 43,
 43,
 35,
 31,
 43,
 43,
 43,
 29,
 43,
 15,
 35,
 43,
 29,
 51,
 35,
 43,
 11,
 29,
 43,
 25,
 43,
 43,
 17,
 43,
 43,
 25,
 41,
 43,
 11,
 29,
 11,
 43,
 43,
 11,
 43,
 29,
 29,
 43,
 43,
 43,
 31,
 43,
 13,
 43,
 13,
 29,
 11,
 29,
 49,
 29,
 43,
 43,
 13,
 17,
 29,
 43,
 35,
 43,
 43,
 51,
 29,
 43,
 43,
 29,
 51,
 43,
 43,
 19,
 43,
 29,
 43,
 43,
 43,
 29,
 11,
 29,
 41,
 41,
 43,
 43,
 29,
 51,
 43,
 11,
 43,
 13,
 43,
 43,
 43,
 43,
 43,
 29,
 43,
 43,
 51,
 43,
 43,
 41,
 43,
 43,
 43,
 43,
 17,
 43,
 43,
 43,
 25,
 25,
 43,
 43,
 43,
 29,
 25,
 51,
 43,
 43,
 29,
 43,
 43,
 29,
 43,
 43,
 43,
 25,
 43,
 43,
 35,
 43,
 41,
 35,
 49,
 43,
 41,
 53,
 43,
 47,
 13,
 43,
 43,
 17,
 51,
 43,
 13,
 11,
 43,
 43,
 19,
 13,
 43,
 43,
 43,
 13,
 29,
 43,
 43,
 13,
 43,
 35,
 29,
 43,
 43,
 43,
 43,
 13,
 43,
 43,
 51,
 47,
 11,
 35,
 49,
 25,
 27,
 43,
 41,
 43,
 43,
 17,
 43,
 43,
 41,
 13,
 43,
 29,
 51,
 27,
 25,
 51,
 35,
 13,
 25,
 35,
 13,
 43,
 43,
 13,
 43,
 49,
 13,
 43,
 49,
 29,
 29,
 31,
 35,
 35,
 51,
 35,
 43,
 25,
 43,
 39,
 43,
 43,
 41,
 43,
 29,
 43,
 35,
 53,
 15,
 15,
 25,
 11,
 43,
 43,
 43,
 43,
 43,
 21,
 29,
 11,
 47,
 43,
 43,
 43,
 43,
 43,
 11,
 43,
 43,
 43,
 43,
 43,
 11,
 25,
 43,
 43,
 17,
 47,
 43,
 13,
 43,
 49,
 43,
 43,
 13,
 29,
 43,
 43,
 25,
 41,
 43,
 51,
 43,
 29,
 29,
 43,
 43,
 11,
 43,
 53,
 35,
 11,
 41,
 43,
 11,
 11,
 19,
 13,
 11,
 47,
 29,
 25,
 43,
 43,
 43,
 43,
 25,
 53,
 43,
 29,
 49,
 13,
 43,
 25,
 25,
 41,
 43,
 49,
 27,
 29,
 43,
 43,
 43,
 43,
 43,
 25,
 43,
 35,
 43,
 43,
 17,
 43,
 11,
 25,
 29,
 43,
 53,
 25,
 11,
 29,
 43,
 43,
 13,
 11,
 41,
 29,
 43,
 43,
 43,
 25,
 51,
 35,
 29,
 41,
 43,
 25,
 43,
 35,
 25,
 43,
 43,
 39,
 43,
 25,
 43,
 43,
 53,
 13,
 15,
 13,
 51,
 43,
 11,
 29,
 27,
 43,
 43,
 25,
 25,
 43,
 35,
 43,
 43,
 29,
 53,
 29,
 29,
 43,
 43,
 43,
 35,
 13,
 43,
 13,
 53,
 13,
 53,
 43,
 43,
 43,
 43,
 11,
 43,
 11,
 11,
 25,
 47,
 43,
 51,
 51,
 41,
 53,
 29,
 29,
 53,
 41,
 17,
 41,
 43,
 43,
 11,
 43,
 11,
 43,
 13,
 41,
 43,
 43,
 43,
 43,
 53,
 43,
 43,
 49,
 35,
 41,
 43,
 13,
 43,
 29,
 43,
 43,
 43,
 43,
 43,
 11,
 43,
 13,
 25,
 43,
 43,
 13,
 43,
 13,
 25,
 47,
 43,
 25,
 43,
 43,
 47,
 29,
 43,
 25,
 29,
 13,
 43,
 41,
 43,
 43,
 27,
 27,
 43,
 13,
 29,
 51,
 29,
 25,
 29,
 41,
 ...]

In [29]:
submission = pd.DataFrame(pred_class, index=test.index, columns=['PRED']).reset_index()
submission.to_csv('my_pred27.csv', index=False)

## 3.XGB

In [30]:
import joblib

import pandas as pd
import numpy as np


from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler , MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [63]:
train = pd.read_csv('../data/train_ver03.csv', index_col='STU_ID')
y = train.F3ONET2CURR
x = train.drop(columns='F3ONET2CURR')

In [64]:
test = pd.read_csv('../data/test_ver03.csv', index_col='STU_ID')
test = test.drop(columns='F3ONET2CURR')
test.head()

,BYSTUWT,BYSEX,BYRACE,BYSTLANG,BYHOMLNG,BYSTLNG2,BYDOB_P,BYFCOMP,BYPARED,BYMOTHED,...,BYS24C,BYS24D,BYS24E,BYS28,BYS71A,BYS71B,BYS71C,BYS71D,BYS71E,BYS71F
STU_ID,,,,,,,,,,,,,,,,,,,,,
310221,292.1255,2.0,6.0,1.0,1.0,4,198412.0,2.0,4.0,4.0,...,4.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,0.0
228218,281.6741,1.0,7.0,1.0,1.0,4,198507.0,6.0,1.0,1.0,...,3.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
179231,275.0641,1.0,7.0,1.0,1.0,4,198607.0,1.0,4.0,4.0,...,3.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
215101,149.2901,2.0,3.0,1.0,1.0,4,198507.0,2.0,3.0,1.0,...,4.0,1.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
245121,186.5067,1.0,7.0,1.0,1.0,4,198601.0,5.0,3.0,3.0,...,2.0,2.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0

In [82]:
with open('../data/my_val.pkl2', 'rb') as f:
    data = joblib.load(f)
locals().update(data)
del data

In [2]:
# with open('../data/my_val.pkl2', 'rb') as f:
#     data = joblib.load(f)
# locals().update(data)
# del data
# np.random.seed(1234)

In [84]:
x

,BYSTUWT,BYSEX,BYRACE,BYSTLANG,BYHOMLNG,BYSTLNG2,BYDOB_P,BYFCOMP,BYPARED,BYMOTHED,...,BYS24C,BYS24D,BYS24E,BYS28,BYS71A,BYS71B,BYS71C,BYS71D,BYS71E,BYS71F
STU_ID,,,,,,,,,,,,,,,,,,,,,
281214,93.52160,1.0,2.0,1.0,1.0,4,198601.0,1.0,1.0,1.0,...,1.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
101126,83.57963,2.0,2.0,0.0,5.0,1,198410.0,1.0,1.0,1.0,...,1.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
278210,184.90160,2.0,4.0,0.0,2.0,2,198606.0,1.0,1.0,1.0,...,2.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0
391108,112.75530,1.0,7.0,1.0,1.0,4,198605.0,1.0,6.0,6.0,...,2.0,1.0,1.0,3.0,0.0,1.0,0.0,0.0,1.0,0.0
288213,292.12550,1.0,3.0,1.0,1.0,4,198412.0,1.0,4.0,4.0,...,2.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150111,292.12550,1.0,7.0,1.0,1.0,4,198508.0,1.0,3.0,2.0,...,3.0,2.0,1.0,2.0,0.0,0.0,1.0,0.0,1.0,0.0
265213,203.47770,2.0,7.0,1.0,1.0,4,198603.0,1.0,5.0,5.0,...,2.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0
428111,107.05950,2.0,7.0,1.0,1.0,4,198603.0,1.0,2.0,2.0,...,3.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
204207,96.18130,1.0,3.0,1.0,1.0,4,198607.0,1.0,1.0,1.0,...,2.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
265208,203.47770,2.0,7.0,1.0,1.0,4,198511.0,3.0,2.0,2.0,...,1.0,1.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0

In [85]:
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV

In [93]:
# xgb = XGBClassifier(objective='multi:softmax',num_classes=20)
# param = {'n_estimators': np.arange(2, 301),
#          'learning_rate' : np.arange(1,51)/100,
#          'max_depth':np.arange(2,11)}

xgb_best = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain',learning_rate=0.13, max_delta_step=0, max_depth=16,
              min_child_weight=1,  
              n_estimators=109, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

# xgb_best = XGBClassifier(booster='gbtree', objective='multi:softmax', 
#                         n_estimators=100,  max_depth=10)

In [16]:
# xgb_best = RandomizedSearchCV(estimator=xgb, param_distributions=param,
#                              n_iter=20, cv=4, scoring='accuracy', n_jobs=-1,
#                              verbose=1)

In [94]:
xgb_best.fit(x,y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.13, max_delta_step=0, max_depth=16,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=109, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [18]:
# xgb_best.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.13, max_delta_step=0, max_depth=2,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=109, n_jobs=0, num_classes=20, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [95]:
from sklearn.metrics import accuracy_score
accuracy_score(val_y, xgb_best.predict(val_x))

0.24708718360787466

In [58]:
test = pd.read_csv('../data/test_ver02.csv', index_col='STU_ID')
test = test.drop(columns='F3ONET2CURR')
test.head()

,BYSTUWT,BYSEX,BYRACE,BYSTLANG,BYHOMLNG,BYSTLNG2,BYDOB_P,BYFCOMP,BYPARED,BYMOTHED,...,BYS24C,BYS24D,BYS24E,BYS28,BYS71A,BYS71B,BYS71C,BYS71D,BYS71E,BYS71F
STU_ID,,,,,,,,,,,,,,,,,,,,,
310221,575.7933,2.0,6.0,1.0,1.0,4,198412.0,2.0,4.0,4.0,...,4.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,0.0
228218,281.6741,1.0,7.0,1.0,1.0,4,198507.0,6.0,1.0,1.0,...,3.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
179231,275.0641,1.0,7.0,1.0,1.0,4,198607.0,1.0,4.0,4.0,...,3.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
215101,149.2901,2.0,3.0,1.0,1.0,4,198507.0,2.0,3.0,1.0,...,4.0,1.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
245121,186.5067,1.0,7.0,1.0,1.0,4,198601.0,5.0,3.0,3.0,...,2.0,2.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0

In [96]:
# pred = xgb_best.best_estimator_.predict(test)
pred = xgb_best.predict(test)
pred

array([43, 47, 11, ..., 43, 43, 17], dtype=int64)

In [90]:
pred.shape

(2479,)

In [97]:
submission = pd.DataFrame(pred, index=test.index, columns=['PRED']).reset_index()
submission

      STU_ID  PRED
0     310221    43
1     228218    47
2     179231    11
3     215101    41
4     245121    53
...      ...   ...
2474  439214    43
2475  106206    13
2476  272131    43
2477  350228    43
2478  297108    17

[2479 rows x 2 columns]

In [98]:
submission.to_csv('my_pred34.csv', index=False)

## Auto Encoder

In [1]:
import joblib
import numpy as np
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler , MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [3]:
with open('../data/my_val.pkl','rb') as f:
    data = joblib.load(f)
print(data.keys())
locals().update(data)
del data

dict_keys(['x', 'y', 'val_x', 'val_y'])

In [4]:
test = pd.read_csv('../data/test_ver03.csv', index_col='STU_ID')
test = test.drop(columns='F3ONET2CURR')
test.head()

,BYSTUWT,BYSEX,BYRACE,BYSTLANG,BYHOMLNG,BYSTLNG2,BYDOB_P,BYFCOMP,BYPARED,BYMOTHED,...,BYS24C,BYS24D,BYS24E,BYS28,BYS71A,BYS71B,BYS71C,BYS71D,BYS71E,BYS71F
STU_ID,,,,,,,,,,,,,,,,,,,,,
310221,292.1255,2.0,6.0,1.0,1.0,4,198412.0,2.0,4.0,4.0,...,4.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,0.0
228218,281.6741,1.0,7.0,1.0,1.0,4,198507.0,6.0,1.0,1.0,...,3.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
179231,275.0641,1.0,7.0,1.0,1.0,4,198607.0,1.0,4.0,4.0,...,3.0,1.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
215101,149.2901,2.0,3.0,1.0,1.0,4,198507.0,2.0,3.0,1.0,...,4.0,1.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
245121,186.5067,1.0,7.0,1.0,1.0,4,198601.0,5.0,3.0,3.0,...,2.0,2.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0

In [6]:
minmax = MinMaxScaler()
x_tr = minmax.fit_transform(x)
val_x_tr = minmax.fit_transform(val_x)
test_tr= minmax.fit_transform(test)

In [14]:
idx2class = {}
for i, v in enumerate(y.unique()):
    idx2class[i] = v

class2idx = {v:i for i,v in idx2class.items()}

In [17]:
y_tr = y.replace(class2idx)
val_y_tr = val_y.replace(class2idx)

In [20]:
import tensorflow as tf
from tensorflow import keras

In [21]:
x_tr.shape

(7466, 151)

In [29]:
stacked_encoder = keras.models.Sequential([
                  keras.layers.Input(shape=(x_tr.shape[1],)),
                  keras.layers.Dense(64, activation='relu'),
                  keras.layers.Dense(32, activation='relu')])

stacked_decoder = keras.models.Sequential([
                  keras.layers.Dense(64, activation='relu', input_shape=[32]),
                  keras.layers.Dense(x_tr.shape[1], activation='relu')
])
stacked_ae = keras.models.Sequential([stacked_encoder, stacked_decoder])

In [30]:
epochs = 100
batch = 128
stacked_ae.compile(loss='mean_squared_error',optimizer='RMSProp',
              metrics=['mse'])
stacked_ae.fit(x_tr, x_tr, batch_size=128, epochs=epochs, validation_data=(val_x_tr, val_x_tr))

Epoch 1/100
59/59 [==============================] - 0s 5ms/step - loss: 0.1271 - mse: 0.1271 - val_loss: 0.1099 - val_mse: 0.1099
Epoch 2/100
59/59 [==============================] - 0s 3ms/step - loss: 0.1036 - mse: 0.1036 - val_loss: 0.1011 - val_mse: 0.1011
Epoch 3/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0937 - mse: 0.0937 - val_loss: 0.0862 - val_mse: 0.0862
Epoch 4/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0840 - mse: 0.0840 - val_loss: 0.0818 - val_mse: 0.0818
Epoch 5/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0780 - mse: 0.0780 - val_loss: 0.0744 - val_mse: 0.0744
Epoch 6/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0729 - mse: 0.0729 - val_loss: 0.0724 - val_mse: 0.0724
Epoch 7/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0670 - mse: 0.0670 - val_loss: 0.0656 - val_mse: 0.0656
Epoch 8/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0642 - mse: 0.0642 - val_loss: 0.0638 - val_mse: 0.0638
Epoch 9/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0626 - mse: 0.0626 - val_loss: 0.0584 - val_mse: 0.0584
Epoch 10/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0571 - mse: 0.0571 - val_loss: 0.0576 - val_mse: 0.0576
Epoch 11/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0552 - mse: 0.0552 - val_loss: 0.0557 - val_mse: 0.0557
Epoch 12/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0542 - mse: 0.0542 - val_loss: 0.0541 - val_mse: 0.0541
Epoch 13/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0529 - mse: 0.0529 - val_loss: 0.0527 - val_mse: 0.0527
Epoch 14/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0521 - mse: 0.0521 - val_loss: 0.0523 - val_mse: 0.0523
Epoch 15/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0516 - mse: 0.0516 - val_loss: 0.0531 - val_mse: 0.0531
Epoch 16/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0511 - mse: 0.0511 - val_loss: 0.0522 - val_mse: 0.0522
Epoch 17/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0507 - mse: 0.0507 - val_loss: 0.0516 - val_mse: 0.0516
Epoch 18/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0502 - mse: 0.0502 - val_loss: 0.0503 - val_mse: 0.0503
Epoch 19/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0499 - mse: 0.0499 - val_loss: 0.0501 - val_mse: 0.0501
Epoch 20/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0496 - mse: 0.0496 - val_loss: 0.0503 - val_mse: 0.0503
Epoch 21/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0493 - mse: 0.0493 - val_loss: 0.0490 - val_mse: 0.0490
Epoch 22/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0473 - mse: 0.0473 - val_loss: 0.0478 - val_mse: 0.0478
Epoch 23/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0464 - mse: 0.0464 - val_loss: 0.0433 - val_mse: 0.0433
Epoch 24/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0403 - mse: 0.0403 - val_loss: 0.0410 - val_mse: 0.0410
Epoch 25/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0399 - mse: 0.0399 - val_loss: 0.0404 - val_mse: 0.0404
Epoch 26/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0395 - mse: 0.0395 - val_loss: 0.0398 - val_mse: 0.0398
Epoch 27/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0392 - mse: 0.0392 - val_loss: 0.0406 - val_mse: 0.0406
Epoch 28/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0391 - mse: 0.0391 - val_loss: 0.0394 - val_mse: 0.0394
Epoch 29/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0389 - mse: 0.0389 - val_loss: 0.0398 - val_mse: 0.0398
Epoch 30/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0387 - mse: 0.0387 - val_loss: 0.0395 - val_mse: 0.0395
Epoch 31/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0386 - mse: 0.0386 - val_loss: 0.0399 - val_mse: 0.0399
Epoch 32/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0375 - mse: 0.0375 - val_loss: 0.0376 - val_mse: 0.0376
Epoch 33/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0368 - mse: 0.0368 - val_loss: 0.0370 - val_mse: 0.0370
Epoch 34/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0359 - mse: 0.0359 - val_loss: 0.0358 - val_mse: 0.0358
Epoch 35/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0353 - mse: 0.0353 - val_loss: 0.0369 - val_mse: 0.0369
Epoch 36/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0349 - mse: 0.0349 - val_loss: 0.0359 - val_mse: 0.0359
Epoch 37/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0348 - mse: 0.0348 - val_loss: 0.0361 - val_mse: 0.0361
Epoch 38/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0345 - mse: 0.0345 - val_loss: 0.0355 - val_mse: 0.0355
Epoch 39/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0344 - mse: 0.0344 - val_loss: 0.0342 - val_mse: 0.0342
Epoch 40/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0341 - mse: 0.0341 - val_loss: 0.0365 - val_mse: 0.0365
Epoch 41/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0339 - mse: 0.0339 - val_loss: 0.0350 - val_mse: 0.0350
Epoch 42/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0338 - mse: 0.0338 - val_loss: 0.0340 - val_mse: 0.0340
Epoch 43/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0336 - mse: 0.0336 - val_loss: 0.0348 - val_mse: 0.0348
Epoch 44/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0334 - mse: 0.0334 - val_loss: 0.0343 - val_mse: 0.0343
Epoch 45/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0333 - mse: 0.0333 - val_loss: 0.0343 - val_mse: 0.0343
Epoch 46/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0332 - mse: 0.0332 - val_loss: 0.0335 - val_mse: 0.0335
Epoch 47/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0330 - mse: 0.0330 - val_loss: 0.0341 - val_mse: 0.0341
Epoch 48/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0329 - mse: 0.0329 - val_loss: 0.0347 - val_mse: 0.0347
Epoch 49/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0327 - mse: 0.0327 - val_loss: 0.0340 - val_mse: 0.0340
Epoch 50/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0327 - mse: 0.0327 - val_loss: 0.0345 - val_mse: 0.0345
Epoch 51/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0326 - mse: 0.0326 - val_loss: 0.0344 - val_mse: 0.0344
Epoch 52/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0325 - mse: 0.0325 - val_loss: 0.0334 - val_mse: 0.0334
Epoch 53/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0324 - mse: 0.0324 - val_loss: 0.0343 - val_mse: 0.0343
Epoch 54/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0322 - mse: 0.0322 - val_loss: 0.0326 - val_mse: 0.0326
Epoch 55/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0321 - mse: 0.0321 - val_loss: 0.0323 - val_mse: 0.0323
Epoch 56/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0320 - mse: 0.0320 - val_loss: 0.0335 - val_mse: 0.0335
Epoch 57/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0318 - mse: 0.0318 - val_loss: 0.0329 - val_mse: 0.0329
Epoch 58/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0316 - mse: 0.0316 - val_loss: 0.0320 - val_mse: 0.0320
Epoch 59/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0308 - mse: 0.0308 - val_loss: 0.0312 - val_mse: 0.0312
Epoch 60/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0300 - mse: 0.0300 - val_loss: 0.0302 - val_mse: 0.0302
Epoch 61/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0298 - mse: 0.0298 - val_loss: 0.0307 - val_mse: 0.0307
Epoch 62/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0297 - mse: 0.0297 - val_loss: 0.0301 - val_mse: 0.0301
Epoch 63/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0296 - mse: 0.0296 - val_loss: 0.0301 - val_mse: 0.0301
Epoch 64/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0295 - mse: 0.0295 - val_loss: 0.0299 - val_mse: 0.0299
Epoch 65/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0295 - mse: 0.0295 - val_loss: 0.0293 - val_mse: 0.0293
Epoch 66/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0294 - mse: 0.0294 - val_loss: 0.0297 - val_mse: 0.0297
Epoch 67/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0293 - mse: 0.0293 - val_loss: 0.0300 - val_mse: 0.0300
Epoch 68/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0293 - mse: 0.0293 - val_loss: 0.0294 - val_mse: 0.0294
Epoch 69/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0292 - mse: 0.0292 - val_loss: 0.0296 - val_mse: 0.0296
Epoch 70/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0291 - mse: 0.0291 - val_loss: 0.0298 - val_mse: 0.0298
Epoch 71/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0291 - mse: 0.0291 - val_loss: 0.0294 - val_mse: 0.0294
Epoch 72/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0290 - mse: 0.0290 - val_loss: 0.0301 - val_mse: 0.0301
Epoch 73/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0290 - mse: 0.0290 - val_loss: 0.0293 - val_mse: 0.0293
Epoch 74/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0289 - mse: 0.0289 - val_loss: 0.0301 - val_mse: 0.0301
Epoch 75/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0288 - mse: 0.0288 - val_loss: 0.0292 - val_mse: 0.0292
Epoch 76/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0288 - mse: 0.0288 - val_loss: 0.0303 - val_mse: 0.0303
Epoch 77/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0288 - mse: 0.0288 - val_loss: 0.0299 - val_mse: 0.0299
Epoch 78/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0287 - mse: 0.0287 - val_loss: 0.0301 - val_mse: 0.0301
Epoch 79/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0287 - mse: 0.0287 - val_loss: 0.0292 - val_mse: 0.0292
Epoch 80/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0286 - mse: 0.0286 - val_loss: 0.0295 - val_mse: 0.0295
Epoch 81/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0285 - mse: 0.0285 - val_loss: 0.0300 - val_mse: 0.0300
Epoch 82/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0286 - mse: 0.0286 - val_loss: 0.0302 - val_mse: 0.0302
Epoch 83/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0285 - mse: 0.0285 - val_loss: 0.0291 - val_mse: 0.0291
Epoch 84/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0284 - mse: 0.0284 - val_loss: 0.0307 - val_mse: 0.0307
Epoch 85/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0284 - mse: 0.0284 - val_loss: 0.0291 - val_mse: 0.0291
Epoch 86/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0283 - mse: 0.0283 - val_loss: 0.0286 - val_mse: 0.0286
Epoch 87/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0283 - mse: 0.0283 - val_loss: 0.0297 - val_mse: 0.0297
Epoch 88/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0282 - mse: 0.0282 - val_loss: 0.0287 - val_mse: 0.0287
Epoch 89/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0282 - mse: 0.0282 - val_loss: 0.0288 - val_mse: 0.0288
Epoch 90/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0281 - mse: 0.0281 - val_loss: 0.0294 - val_mse: 0.0294
Epoch 91/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0281 - mse: 0.0281 - val_loss: 0.0288 - val_mse: 0.0288
Epoch 92/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0280 - mse: 0.0280 - val_loss: 0.0289 - val_mse: 0.0289
Epoch 93/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0280 - mse: 0.0280 - val_loss: 0.0291 - val_mse: 0.0291
Epoch 94/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0279 - mse: 0.0279 - val_loss: 0.0287 - val_mse: 0.0287
Epoch 95/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0279 - mse: 0.0279 - val_loss: 0.0284 - val_mse: 0.0284
Epoch 96/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0279 - mse: 0.0279 - val_loss: 0.0281 - val_mse: 0.0281
Epoch 97/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0278 - mse: 0.0278 - val_loss: 0.0289 - val_mse: 0.0289
Epoch 98/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0277 - mse: 0.0277 - val_loss: 0.0284 - val_mse: 0.0284
Epoch 99/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0276 - mse: 0.0276 - val_loss: 0.0287 - val_mse: 0.0287
Epoch 100/100
59/59 [==============================] - 0s 3ms/step - loss: 0.0276 - mse: 0.0276 - val_loss: 0.0278 - val_mse: 0.0278

In [53]:
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.layers import Input, Dense,BatchNormalization
from tensorflow.keras.optimizers import Adam

In [42]:
x_auto = stacked_ae.predict(x_tr)
val_x_auto = stacked_ae.predict(val_x_tr)
test_auto = stacked_ae.predict(test_tr)

In [48]:
x_auto.shape[1]

151

In [58]:
my_nn02 = Sequential([
            Input(shape=(x_auto.shape[1],)),
              Dense(128, activation ='relu', kernel_initializer='he_normal'),
              BatchNormalization(),
              Dense(64, activation = 'relu', kernel_initializer='he_normal', use_bias=False),
              BatchNormalization(),
              Dense(32, activation ='relu', kernel_initializer='he_normal'),
              BatchNormalization(),
              Dense(y_tr.nunique(), activation='softmax')])
my_nn02.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_20 (Dense)             (None, 128)               19456
_________________________________________________________________
batch_normalization_3 (Batch (None, 128)               512
_________________________________________________________________
dense_21 (Dense)             (None, 64)                8192
_________________________________________________________________
batch_normalization_4 (Batch (None, 64)                256
_________________________________________________________________
dense_22 (Dense)             (None, 32)                2080
_________________________________________________________________
batch_normalization_5 (Batch (None, 32)                128
_________________________________________________________________
dense_23 (Dense)             (None, 20)                660
=================================================================
Total params: 31,284
Trainable params: 30,836
Non-trainable params: 448
_________________________________________________________________

In [59]:
epochs = 50
batch = 128
optimizer = Adam(lr=0.001, beta_1=0.9, beta_2=0.999)
my_nn02.compile(loss='sparse_categorical_crossentropy',optimizer=optimizer,
              metrics=['acc'])
my_nn02.fit(x_auto, y_tr, batch_size=batch, epochs=epochs)

Epoch 1/50
59/59 [==============================] - 0s 3ms/step - loss: 3.1255 - acc: 0.0952
Epoch 2/50
59/59 [==============================] - 0s 3ms/step - loss: 2.7340 - acc: 0.1725
Epoch 3/50
59/59 [==============================] - 0s 3ms/step - loss: 2.6073 - acc: 0.2001
Epoch 4/50
59/59 [==============================] - 0s 3ms/step - loss: 2.5281 - acc: 0.2144
Epoch 5/50
59/59 [==============================] - 0s 3ms/step - loss: 2.4688 - acc: 0.2254
Epoch 6/50
59/59 [==============================] - 0s 3ms/step - loss: 2.4267 - acc: 0.2335
Epoch 7/50
59/59 [==============================] - 0s 3ms/step - loss: 2.3952 - acc: 0.2442
Epoch 8/50
59/59 [==============================] - 0s 3ms/step - loss: 2.3654 - acc: 0.2509
Epoch 9/50
59/59 [==============================] - 0s 3ms/step - loss: 2.3389 - acc: 0.2609
Epoch 10/50
59/59 [==============================] - 0s 3ms/step - loss: 2.3236 - acc: 0.2596
Epoch 11/50
59/59 [==============================] - 0s 3ms/step - loss: 2.2968 - acc: 0.2684
Epoch 12/50
59/59 [==============================] - 0s 3ms/step - loss: 2.2744 - acc: 0.2746
Epoch 13/50
59/59 [==============================] - 0s 3ms/step - loss: 2.2545 - acc: 0.2811
Epoch 14/50
59/59 [==============================] - 0s 3ms/step - loss: 2.2296 - acc: 0.2904
Epoch 15/50
59/59 [==============================] - 0s 3ms/step - loss: 2.2054 - acc: 0.3003
Epoch 16/50
59/59 [==============================] - 0s 3ms/step - loss: 2.1901 - acc: 0.2973
Epoch 17/50
59/59 [==============================] - 0s 3ms/step - loss: 2.1717 - acc: 0.3069
Epoch 18/50
59/59 [==============================] - 0s 3ms/step - loss: 2.1582 - acc: 0.3093
Epoch 19/50
59/59 [==============================] - 0s 3ms/step - loss: 2.1355 - acc: 0.3232
Epoch 20/50
59/59 [==============================] - 0s 3ms/step - loss: 2.1127 - acc: 0.3256
Epoch 21/50
59/59 [==============================] - 0s 3ms/step - loss: 2.1056 - acc: 0.3314
Epoch 22/50
59/59 [==============================] - 0s 3ms/step - loss: 2.0812 - acc: 0.3339
Epoch 23/50
59/59 [==============================] - 0s 3ms/step - loss: 2.0695 - acc: 0.3373
Epoch 24/50
59/59 [==============================] - 0s 3ms/step - loss: 2.0461 - acc: 0.3497
Epoch 25/50
59/59 [==============================] - 0s 3ms/step - loss: 2.0362 - acc: 0.3468
Epoch 26/50
59/59 [==============================] - 0s 3ms/step - loss: 2.0193 - acc: 0.3612
Epoch 27/50
59/59 [==============================] - 0s 3ms/step - loss: 1.9970 - acc: 0.3651
Epoch 28/50
59/59 [==============================] - 0s 3ms/step - loss: 1.9822 - acc: 0.3765
Epoch 29/50
59/59 [==============================] - 0s 3ms/step - loss: 1.9598 - acc: 0.3750
Epoch 30/50
59/59 [==============================] - 0s 3ms/step - loss: 1.9528 - acc: 0.3788
Epoch 31/50
59/59 [==============================] - 0s 3ms/step - loss: 1.9256 - acc: 0.3867
Epoch 32/50
59/59 [==============================] - 0s 3ms/step - loss: 1.9133 - acc: 0.3918
Epoch 33/50
59/59 [==============================] - 0s 4ms/step - loss: 1.9066 - acc: 0.3880
Epoch 34/50
59/59 [==============================] - 0s 3ms/step - loss: 1.8953 - acc: 0.3963
Epoch 35/50
59/59 [==============================] - 0s 3ms/step - loss: 1.8702 - acc: 0.4045
Epoch 36/50
59/59 [==============================] - 0s 3ms/step - loss: 1.8492 - acc: 0.4101
Epoch 37/50
59/59 [==============================] - 0s 3ms/step - loss: 1.8364 - acc: 0.4155
Epoch 38/50
59/59 [==============================] - 0s 3ms/step - loss: 1.8207 - acc: 0.4250
Epoch 39/50
59/59 [==============================] - 0s 3ms/step - loss: 1.8120 - acc: 0.4216
Epoch 40/50
59/59 [==============================] - 0s 3ms/step - loss: 1.7899 - acc: 0.4275
Epoch 41/50
59/59 [==============================] - 0s 3ms/step - loss: 1.7804 - acc: 0.4330
Epoch 42/50
59/59 [==============================] - 0s 3ms/step - loss: 1.7632 - acc: 0.4384
Epoch 43/50
59/59 [==============================] - 0s 3ms/step - loss: 1.7550 - acc: 0.4348
Epoch 44/50
59/59 [==============================] - 0s 3ms/step - loss: 1.7479 - acc: 0.4447
Epoch 45/50
59/59 [==============================] - 0s 3ms/step - loss: 1.7261 - acc: 0.4537
Epoch 46/50
59/59 [==============================] - 0s 3ms/step - loss: 1.7095 - acc: 0.4445
Epoch 47/50
59/59 [==============================] - 0s 3ms/step - loss: 1.7015 - acc: 0.4525
Epoch 48/50
59/59 [==============================] - 0s 3ms/step - loss: 1.6939 - acc: 0.4581
Epoch 49/50
59/59 [==============================] - 0s 3ms/step - loss: 1.6955 - acc: 0.4585
Epoch 50/50
59/59 [==============================] - 0s 3ms/step - loss: 1.6607 - acc: 0.4630

In [60]:
my_nn02.evaluate(val_x_auto, val_y_tr)

78/78 [==============================] - 0s 2ms/step - loss: 3.3684 - acc: 0.1559

[3.3683559894561768, 0.15588590502738953]

In [46]:
pred = my_nn02.predict(test_auto)
pred_class = [idx2class[i] for i in pred.argmax(axis=1)]

In [47]:
submission = pd.DataFrame(pred_class, index=test.index, columns=['PRED']).reset_index()
submission.to_csv('my_pred15.csv', index=False)